---
- name: master play
  hosts: all
  tasks:
    - name: Directory task
      ansible.builtin.file:
        path: "{{ DIRECTORY }}"
        state: directory
    - name: File task
      ansible.builtin.file:
        path: "{{ FILE }}"
        state: touch
    - name: Copy task
      ansible.builtin.copy:
        dest: "{{ DIRECTORY }}/{{ FILE }}"
        content: "{{ CONTENT }}"
